import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import { useEffect, useState } from 'react'
import Pokedex from '../components/pokedex'

export default function Home() {
  let [pokemons, setPokemons] = useState([])

  useEffect(() => {
    fetch("https://pokeapi.co/api/v2/pokedex/2")
      .then(response => response.json())
      .then(data => setPokemons(data.pokemon_entries))
  }, [])

  /*   { console.log(pokemons) } */

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>


        <Pokedex>
          {pokemons.map((pokemon) => (
            <>
              <Cards key={pokemon.entry_number} name={pokemon.pokemon_species.name} number={pokemon.entry_number} image={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/${pokemon.entry_number}.png`} />

            </>
          ))}
        </Pokedex>
      </Main>
    </Container>
  )
}
